# [DO NOT MODIFY] Automatically generated by EquationUtil().LinearEquationSystemSolverFileMaker
from sympy import symbols
from sympy.solvers.solveset import linsolve
import os
from util.jsonhandler import Handler


current_directory = os.path.dirname(__file__)
a,b,c = symbols("a,b,c")
equation_solution = linsolve(['2*a-2*c', '2*b-4*c'],(a,b,c))


x = symbols(str(c))
equation_solution = [expr.subs(x, 1) for expr in equation_solution][0]


handler_object = Handler(file_path=r"d:\p\Project\Python\CREB\dev")
handler_object.write()

handler_object.update(key="equation_solution",value=str(equation_solution))
    